name: Go application build pipeline - app-ci
on:
  push:
    branches:
      - master

jobs:
  build-app:
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Go 1.20
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.x

      - name: Check for GitLeaks
        uses: gitleaks/gitleaks-action@v2
        with:
          TOKEN: ${{ secrets.TOKEN }}

      - name: SonarQube Scan
        if: ${{ env.SKIP_SONAR != 'true' }}
        uses: sonarsource/sonarqube-scan-action@v2.1.0

      - name: SonarQube Quality Gate check
        if: ${{ env.SKIP_SONAR != 'true' }}
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@v1
        timeout-minutes: 5

      - name: Build Code
        run: |
          echo "Building the Go application ..."
          go build -o go-web-app

      - name: Run Tests
        run: go test ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-web-app:latest,${{ secrets.DOCKERHUB_USERNAME }}/go-web-app:${{ github.run_id }}

      - name: Update tag in Helm chart
        run: |
          git checkout ${{ github.ref_name }}
          sed -i.bak 's/tag: .*/tag: "${{ github.run_id }}"/' helm/go-web-app-chart/values.yaml
          git config --global user.email "pranavborude2000@gmail.com"
          git config --global user.name "Pranav Borude"
          git add helm/go-web-app-chart/values.yaml
          git commit -m "Update tag in Helm chart"
          git push

      - name: Post Deployment Tests
        run: echo "Running post-deployment tests..."
